name: CodeChecks

on:
  push:
  pull_request:

jobs:
  doctest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      # Install Poetry
      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python3 -

      # Install project dependencies using Poetry
      - name: Install dependencies
        run: poetry install --with dev

      - name: Isort
        run: poetry run isort --profile black .

      - name: Black
        run: poetry run black --check --diff .

      - name: flake8
        run: poetry run flake8 -v --doctests lost_spc

      - name: pyright
        run: poetry run basedpyright

      - name: Code complexity
        run: poetry run complexipy .

      - name: Run tests
        run: poetry run pytest
